name: Pycodestyle

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle nbformat

    - name: Check .py files
      run: |
        find app -name "*.py" -exec pycodestyle {} +
